### ISSUE TITLE
Segmentation Fault in 1.2-arraysAndStrings.cxx

### ISSUE THREAD

**Issue by kkloberdanz** [shyal/cracking-the-coding-interview#2]
Shouldn't c be freed after the assert statement?
From line 31 to 32 in 1.2-arraysAndStrings.cxx

i.e. from this 
    free(c);
    assert(strcmp(c, "raboof") == 0);

to this
    assert(strcmp(c, "raboof") == 0);
    free(c);

**Comment by shyal** [comment]
It certainly should!

**Comment by shyal** [comment]
Fixed. Thanks for your report.

**Comment by kkloberdanz** [comment]
Not a problem! I like the project.
